version: '3'

tasks:
  default:
    cmds:
      - task: conan
      - task: bazel

  conan:
    cmds:
      - conan profile detect --force
      - conan profile path default
      - conan install conanfile.txt --output-folder=builddir/conan --build=missing # --profile conanrc

  bazel:
    cmds:
      - bazel run //src:main
