version: '3'
tasks:
  default:
    dir: ./builddir/autotools
    cmds:
      - autoreconf -vfi ../..
      - ../../configure
      - make -C src
  docker:
    cmds:
      - docker build . --tag bazel-example
