version: '3'
tasks:
  default:
    dir: ./build
    cmds:
      - autoreconf -vfi ..
      - ../configure
      - make -C src
  default2:
    cmds:
      - libtoolize
      - aclocal
      - autoconf
      - automake --add-missing
      - ./configure

  clean: rm -rf autom4te.cache aclocal.m4 configure configure~ depcomp install-sh missing install-sh~ ltmain.sh compile config.guess config.sub build src/Makefile.in config.log config.status libtool src/.deps src/Makefile
  docker:
    cmds:
      - docker build . --tag bazel-example
