cxx_library(
    name="libhello-shared",
    srcs=[
        "hello.h",
        "hello-shared.cc",
    ],
    link_style="shared",
)

cxx_library(
    name="libhello-static",
    srcs=[
        "hello.h",
        "hello-static.cc",
    ],
    # exported_headers = glob(["**/*.hpp"]),
    link_style="static",
)

cxx_binary(
    name="main",
    srcs=[
        "main.cc",
    ],
    link_style = "static",
    deps=[
        ":libhello-static",
        ":libhello-shared",
    ],
)
