version: '3'

tasks:
  default:
    cmds:
      - rm -rf ./builddir/cmake
      - cmake -B ./builddir/cmake -S . -G Ninja -DCMAKE_TOOLCHAIN_FILE=./vcpkg/scripts/buildsystems/vcpkg.cmake
      - cmake --build ./builddir/cmake

  vcpkg-setup:
    cmds:
      - git clone https://github.com/Microsoft/vcpkg.git --depth=1
      - ./vcpkg/bootstrap-vcpkg.sh -disableMetrics

  vcpkg-install:
    cmds:
      - ./vcpkg/vcpkg install

  docker:
    cmds:
      - docker build . --tag bazel-example
