version: '3'

tasks:
  default:
    cmds:
      - rm -rf ./builddir/cmake
      - cmake -B ./builddir/cmake -S . -G Ninja
      - cmake --build ./builddir/cmake

  cpm:
    cmds:
      - curl -sSL -o cmake/CPM.cmake https://github.com/cpm-cmake/CPM.cmake/releases/latest/download/get_cpm.cmake

  docker:
    cmds:
      - docker build . --tag bazel-example
