VERSION 0.6
FROM ubuntu:22.04

## for apt to be noninteractive
ENV DEBIAN_FRONTEND noninteractive
ENV DEBCONF_NONINTERACTIVE_SEEN true

RUN apt-get update && apt-get install -y \
  qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools curl git

RUN apt-get update && apt-get install -y g++

RUN curl -sSL -o /usr/local/bin/bazel https://github.com/bazelbuild/bazelisk/releases/download/v1.14.0/bazelisk-linux-amd64 \
  && chmod +x /usr/local/bin/bazel

WORKDIR /code

code:
  COPY main.cpp main.cpp
  COPY mainwindow.ui mainwindow.ui
  COPY mainwindow.h mainwindow.h
  COPY mainwindow.cpp mainwindow.cpp
  COPY BUILD BUILD
  COPY WORKSPACE WORKSPACE

build:
  FROM +code
  RUN bazel build //...
