# Copyright (c) 2018-2022 curoky(cccuroky@gmail.com).
#
# This file is part of learn-qt.
# See https://github.com/curoky/learn-qt for further info.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

workspace(name = "com_github_curoky_qt_example")

load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

git_repository(
    name = "com_justbuchanan_rules_qt",
    branch = "master",
    remote = "https://github.com/justbuchanan/bazel_rules_qt.git",
)

load("@com_justbuchanan_rules_qt//:qt_configure.bzl", "qt_configure")

qt_configure()

load("@local_config_qt//:local_qt.bzl", "local_qt_path")

new_local_repository(
    name = "qt",
    build_file = "@com_justbuchanan_rules_qt//:qt.BUILD",
    path = local_qt_path(),
)

load("@com_justbuchanan_rules_qt//tools:qt_toolchain.bzl", "register_qt_toolchains")

register_qt_toolchains()

# http_archive(
#     name="com_justbuchanan_rules_qt",
#     urls=[
#         "https://github.com/justbuchanan/bazel_rules_qt/archive/refs/heads/master.tar.gz"
#     ],
#     strip_prefix="bazel_rules_qt-master",
#     patch_cmds=[
#         "sed -i -e 's^/usr/include/x86_64-linux-gnu/qt5^/home/linuxbrew/.linuxbrew/opt/qt@5/^g' qt_configure.bzl"
#     ],
# )
