# Copyright (c) 2018-2024 curoky(cccuroky@gmail.com).
#
# This file is part of minimal-example.
# See https://github.com/curoky/minimal-example for further info.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

new_local_repository(
    name = "tensorflow",
    build_file = "//:tf.BUILD",
    path = "/opt/conda/envs/tf2.5/lib/python3.8/site-packages/tensorflow",
)

http_archive(
    name = "rules_cuda",
    sha256 = "c7bf1da41b5a31480a0477f4ced49eed08ab1cb3aff77c704e373cf9c52694f5",
    strip_prefix = "rules_cuda-3482c70dc60d9ab1ad26b768c117fcd61ee12494",
    urls = ["https://github.com/bazel-contrib/rules_cuda/archive/3482c70dc60d9ab1ad26b768c117fcd61ee12494.tar.gz"],
)

load("@rules_cuda//cuda:repositories.bzl", "local_cuda", "register_detected_cuda_toolchains")

local_cuda(
    name = "local_cuda",
    toolkit_path = "/usr/local/cuda-11.4",
)

register_detected_cuda_toolchains()
