name: 'Setup cuda'
description: 'setup cuda'
inputs:
  cuda_version:
    required: false
    default: '12.5'
    description: 'cuda version'
  enable_cudnn:
    required: false
    default: 'false'
    description: 'enable cudnn'
  cudnn_version:
    required: false
    default: '8'
    description: 'cudnn version'

runs:
  using: 'composite'
  steps:
    - name: cache cuda
      id: cache-cuda
      uses: actions/cache@v4
      with:
        path: cuda_pkg_cache
        key: cuda_pkg_cache-${{ inputs.cuda_version }}

    - name: cache cudnn
      id: cache-cudnn
      if: inputs.enable_cudnn == 'true'
      uses: actions/cache@v4
      with:
        path: cudnn_pkg_cache
        key: cudnn_pkg_cache-${{ inputs.cudnn_version }}

    - name: download cuda
      if: steps.cache-cuda.outputs.cache-hit != 'true'
      shell: bash
      run: |
        mkdir -p cuda_pkg_cache
        if [[ ${{ inputs.cuda_version }} == '12.5' ]]; then
          curl -sSL -o cuda_pkg_cache/cuda.deb https://developer.download.nvidia.com/compute/cuda/12.5.0/local_installers/cuda-repo-ubuntu2204-12-5-local_12.5.0-555.42.02-1_amd64.deb
        elif [[ ${{ inputs.cuda_version }} == '12.3' ]]; then
          curl -sSL -o cuda_pkg_cache/cuda.deb https://developer.download.nvidia.com/compute/cuda/12.3.0/local_installers/cuda-repo-ubuntu2204-12-3-local_12.3.0-545.23.06-1_amd64.deb
        elif [[ ${{ inputs.cuda_version }} == '11.4' ]]; then
          curl -sSL -o cuda_pkg_cache/cuda.deb https://developer.download.nvidia.com/compute/cuda/11.4.0/local_installers/cuda-repo-ubuntu2004-11-4-local_11.4.0-470.42.01-1_amd64.deb
        fi

    - name: install cuda
      shell: bash
      run: |
        if [[ ${{ inputs.cuda_version }} == '12.5' ]]; then
          wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-ubuntu2204.pin
          sudo mv cuda-ubuntu2204.pin /etc/apt/preferences.d/cuda-repository-pin-600
          sudo dpkg -i cuda_pkg_cache/cuda.deb
          sudo cp /var/cuda-repo-ubuntu2204-12-5-local/cuda-*-keyring.gpg /usr/share/keyrings/
          sudo apt-get update
          sudo apt-get -y install cuda-toolkit-12-5
        elif [[ ${{ inputs.cuda_version }} == '12.3' ]]; then
          wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-ubuntu2204.pin
          sudo mv cuda-ubuntu2204.pin /etc/apt/preferences.d/cuda-repository-pin-600
          sudo dpkg -i cuda_pkg_cache/cuda.deb
          sudo cp /var/cuda-repo-ubuntu2204-12-3-local/cuda-*-keyring.gpg /usr/share/keyrings/
          sudo apt-get update
          sudo apt-get -y install cuda-toolkit-12-3
        elif [[ ${{ inputs.cuda_version }} == '11.4' ]]; then
          wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-ubuntu2004.pin
          sudo mv cuda-ubuntu2004.pin /etc/apt/preferences.d/cuda-repository-pin-600
          sudo dpkg -i cuda_pkg_cache/cuda.deb
          sudo apt-key add /var/cuda-repo-ubuntu2004-11-4-local/7fa2af80.pub
          sudo apt-get update
          sudo apt-get -y install cuda
        fi

    - name: download cudnn
      if: inputs.enable_cudnn == 'true' && steps.cache-cudnn.outputs.cache-hit != 'true'
      shell: bash
      run: |
        mkdir -p cudnn_pkg_cache
        if [[ ${{ inputs.cudnn_version }} == '8' ]]; then
          curl -sSL -o cudnn_pkg_cache/cudnn.deb https://developer.download.nvidia.com/compute/redist/cudnn/v8.8.0/local_installers/12.0/cudnn-local-repo-ubuntu2204-8.8.0.121_1.0-1_amd64.deb
        elif [[ ${{ inputs.cudnn_version }} == '9' ]]; then
          curl -sSL -o cudnn_pkg_cache/cudnn.deb https://developer.download.nvidia.com/compute/cudnn/9.1.1/local_installers/cudnn-local-repo-ubuntu2204-9.1.1_1.0-1_amd64.deb
        fi

    - name: install cudnn
      if: inputs.enable_cudnn == 'true'
      shell: bash
      run: |
        if [[ ${{ inputs.enable_cudnn }} == 'true' ]]; then
          if [[ ${{ inputs.cudnn_version }} == '8' ]]; then
            sudo dpkg -i cudnn_pkg_cache/cudnn.deb
            sudo cp /var/cudnn-local-repo-ubuntu2204-8.8.0.121/cudnn-*-keyring.gpg /usr/share/keyrings/
            sudo apt-get update -y
            sudo apt-get -y install libcudnn8-dev
          elif [[ ${{ inputs.cudnn_version }} == '9' ]]; then
            sudo dpkg -i cudnn_pkg_cache/cudnn.deb
            sudo cp /var/cudnn-local-repo-ubuntu2204-9.1.1/cudnn-*-keyring.gpg /usr/share/keyrings/
            sudo apt-get update -y
            sudo apt-get -y install cudnn
            sudo apt-get -y install cudnn-cuda-12
          fi
        fi
