VERSION 0.6
FROM ubuntu:22.04

## for apt to be noninteractive
ENV DEBIAN_FRONTEND noninteractive
ENV DEBCONF_NONINTERACTIVE_SEEN true

RUN apt-get update && apt-get install -y build-essential cmake

WORKDIR /code

code:
  COPY CMakeLists.txt CMakeLists.txt
  COPY main.cc main.cc

build:
  FROM +code
  RUN cmake .
  # cache cmake temp files to prevent rebuilding .o files
  # when the .cpp files don't change
  RUN --mount=type=cache,target=/code/CMakeFiles make
  SAVE ARTIFACT main AS LOCAL "builddir/main"

docker:
  COPY +build/main /bin/main
  ENTRYPOINT ["/bin/main"]
  SAVE IMAGE --push earthly/examples:cpp
