name: buck

on:
  push:
    paths:
      - .github/workflows/buck.yaml
      - build-system/buck/**
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  cpp:
    defaults:
      run:
        working-directory: build-system/buck/cpp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
