name: build-system

on:
  push:
    paths:
      - .github/workflows/build-system.yaml
      - build-system/autotools/**
      - build-system/bazel/**
      - build-system/blade/**
      - build-system/buck2/**
      - build-system/meson/**
      - build-system/scons/**
      - build-system/please/**
      - build-system/cmake/**
      - build-system/xmake/**
      - build-system/maven/**
      - build-system/gradle/**
      - build-system/cuda/**
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        path:
          - build-system/autotools/cpp
          - build-system/bazel/basic-cpp
          - build-system/bazel/basic-cpp-nobzlmod
          - build-system/bazel/basic-go
          - build-system/bazel/integrate-conan
          - build-system/bazel/with-libllvm-v2
          - build-system/blade/cpp
          - build-system/buck2/cpp
          - build-system/meson/cpp
          - build-system/scons/cpp
          - build-system/please/cpp
          - build-system/cmake/hello
          - build-system/cmake/with-ccache
          - build-system/cmake/with-conan
          - build-system/cmake/with-cpm
          - build-system/cmake/with-vcpkg
          - build-system/xmake/cpp/hello
          - build-system/xmake/cpp/with-extern-pm
          - build-system/xmake/cpp/with-vcpkg
          - build-system/maven
          - build-system/gradle
          - build-system/cuda/usage/build-with-nvcc
          - build-system/cuda/usage/build-with-bazel-bzlmod
          - build-system/cuda/usage/build-with-bazel

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Homebrew/actions/setup-homebrew@master
      - run: brew install go-task
      - run: task docker
        working-directory: ${{ matrix.path }}
