name: cuda docker

on:
  push:
    paths:
      - .github/workflows/cuda-docker.yaml
      - build-system/cuda/docker/**
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        version:
          - cuda11.4-cudnn8
          - cuda12.3-cudnn8
          - cuda12.3-cudnn9

    runs-on: ubuntu-latest
    steps:
      - uses: jlumbroso/free-disk-space@main
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v2
        with:
          username: curoky
          password: ${{ secrets.DOCKER_TOKEN }}

      - uses: docker/build-push-action@v5
        with:
          context: build-system/cuda/docker
          file: build-system/cuda/docker/${{ matrix.version }}.Dockerfile
          push: true
          tags: curoky/infra-image:${{ matrix.version }}
          cache-from: type=registry,ref=curoky/infra-image:__cache_${{ matrix.version }}
          cache-to: type=registry,ref=curoky/infra-image:__cache_${{ matrix.version }},mode=max
