name: cuda usage

on:
  push:
    paths:
      - .github/workflows/cuda-usage.yaml
      - build-system/cuda/usage/**
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  build-with-bazel:
    defaults:
      run:
        working-directory: build-system/cuda/usage/build-with-bazel
    container:
      image: nvidia/cuda:12.3.2-devel-ubuntu22.04
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bazelbuild/setup-bazelisk@v3
      - run: bazel build :main

  build-with-bazel-bzlmod:
    defaults:
      run:
        working-directory: build-system/cuda/usage/build-with-bazel-bzlmod
    container:
      image: nvidia/cuda:12.3.2-devel-ubuntu22.04
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bazelbuild/setup-bazelisk@v3
      - run: bazel build :main

  build-with-nvcc:
    defaults:
      run:
        working-directory: build-system/cuda/usage/build-with-nvcc
    container:
      image: nvidia/cuda:12.3.2-devel-ubuntu22.04
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: /usr/local/cuda/bin/nvcc -lcudart_static -o main main.cu
