name: gcc

on:
  push:
    paths:
      - .github/workflows/gcc.yaml
      - build-system/gcc/**
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  hello:
    defaults:
      run:
        working-directory: build-system/gcc/hello
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get install -y lld
      - run: ./gcc.sh
