name: meson

on:
  push:
    paths:
      - .github/workflows/meson.yaml
      - build-system/meson/**
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  cpp:
    defaults:
      run:
        working-directory: build-system/meson/cpp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Homebrew/actions/setup-homebrew@master
      - run: brew install meson
      - run: meson setup ./builddir/meson
      - run: meson compile -C ./builddir/meson
      - run: ninja -C ./builddir/meson
      - run: ninja -C ./builddir/meson -f build.ninja -t compdb > compile_commands.json
