name: scons

on:
  push:
    paths:
      - .github/workflows/scons.yaml
      - build-system/scons/**
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  cpp:
    defaults:
      run:
        working-directory: build-system/scons/cpp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Homebrew/actions/setup-homebrew@master

      - run: brew install scons
      - run: scons
      - run: scons -c
